name: Lint and Publish Bicep

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build-armtemplates:
    name: Lint and Publish Bicep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Bicep CLI
        run: az bicep install

      - name: Lint Bicep
        run: az bicep lint --file ./infra/main.bicep

      - name: Publish Bicep as Workflow Artifact
        uses: actions/upload-artifact@v5
        with:
          name: infrastructure_bicep
          path: infra/
