name: Quality Gate

on:
  workflow_dispatch:

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'

      - name: Configure npm retries
        run: |
          npm config set fetch-retries 5
          npm config set fetch-retry-factor 2
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000
          npm config set registry https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Validate threat register
        run: npm run validate:threats

      - name: Run quality gate
        run: xvfb-run -a --server-args="-screen 0 1920x1080x24" npm run quality:gate
