name: Validate Infrastructure

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      resource_token:
        required: true
        type: string
      retain_resources:
        required: true
        type: boolean
      azure_location:
        required: false
        type: string
    outputs:
      endpoint_url:
        description: Azure AI Foundry endpoint emitted by provisioning workflow
        value: ${{ jobs.provision.outputs.endpoint_url || '' }}
      workspace_id:
        description: Diagnostics workspace resource ID
        value: ${{ jobs.provision.outputs.workspace_id || '' }}
      workspace_customer_id:
        description: Diagnostics workspace customer ID used for Data Collector API calls
        value: ${{ jobs.provision.outputs.workspace_customer_id || '' }}
      resource_group_name:
        description: Azure resource group containing VoicePilot assets
        value: ${{ jobs.provision.outputs.resource_group_name || '' }}
      azure_environment_name:
        description: azd environment identifier used for provisioning
        value: ${{ jobs.provision.outputs.azure_environment_name || '' }}
      resource_token:
        description: Token provided by caller to scope ephemeral resources
        value: ${{ inputs.resource_token }}
      target_environment:
        description: Logical deployment environment requested by caller
        value: ${{ inputs.environment }}
      azure_location:
        description: Azure region used during provisioning
        value: ${{ jobs.provision.outputs.azure_location || '' }}

permissions:
  contents: read
  id-token: write

jobs:
  provision:
    name: Provision infrastructure snapshot
    if: ${{ inputs.environment == 'testing' }}
    uses: ./.github/workflows/provision-infrastructure.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      resource_token: ${{ inputs.resource_token }}
      azure_location: ${{ inputs.azure_location }}

  teardown:
    name: Teardown validation environment
    needs: provision
    if: ${{ inputs.environment == 'testing' && inputs.retain_resources == false }}
    uses: ./.github/workflows/delete-infrastructure.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      resource_token: ${{ inputs.resource_token }}
      retain_resources: ${{ inputs.retain_resources }}
      azure_location: ${{ inputs.azure_location }}
